### ISSUE TITLE
Error while trying to run it

### ISSUE THREAD

**Issue by Prchakr** [rishabhkh/nse-fetch#1]
I am trying to run from one of the 3rd party tool which supports JAVA.
I have included the JAR file & when i try to run the example code, got following error.

While executing [invoke] encountered [java.lang.NullPointerException] : [null at com.rishabhk.nsefetch.Nse.getPageAsString(Nse.java:274)]

Please advise

**Comment by rishabhkh** [comment]
Hey Prachkr, I tried running the Example1 code, and it is working. I do no work on this project anymore, so I am afraid I cannot help you more, but I can confirm the existing jar is working. Please make sure you have the same version of dependencies as listed in the Readme page. Good luck!
